/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sApiCoreV1NodeSelector;
import java.io.IOException;

/**
 * VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from.
 */
@ApiModel(description = "VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from.")

public class IoK8sApiCoreV1VolumeNodeAffinity {
  @SerializedName("required")
  private IoK8sApiCoreV1NodeSelector required = null;

  public IoK8sApiCoreV1VolumeNodeAffinity required(IoK8sApiCoreV1NodeSelector required) {
    this.required = required;
    return this;
  }

   /**
   * Required specifies hard node constraints that must be met.
   * @return required
  **/
  @ApiModelProperty(value = "Required specifies hard node constraints that must be met.")
  public IoK8sApiCoreV1NodeSelector getRequired() {
    return required;
  }

  public void setRequired(IoK8sApiCoreV1NodeSelector required) {
    this.required = required;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiCoreV1VolumeNodeAffinity ioK8sApiCoreV1VolumeNodeAffinity = (IoK8sApiCoreV1VolumeNodeAffinity) o;
    return Objects.equals(this.required, ioK8sApiCoreV1VolumeNodeAffinity.required);
  }

  @Override
  public int hashCode() {
    return Objects.hash(required);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiCoreV1VolumeNodeAffinity {\n");
    
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

