/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale;
import io.swagger.client.model.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus;
import java.io.IOException;

/**
 * CustomResourceSubresources defines the status and scale subresources for CustomResources.
 */
@ApiModel(description = "CustomResourceSubresources defines the status and scale subresources for CustomResources.")

public class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources {
  @SerializedName("scale")
  private IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale scale = null;

  @SerializedName("status")
  private IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus status = null;

  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources scale(IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale scale) {
    this.scale = scale;
    return this;
  }

   /**
   * Scale denotes the scale subresource for CustomResources
   * @return scale
  **/
  @ApiModelProperty(value = "Scale denotes the scale subresource for CustomResources")
  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale getScale() {
    return scale;
  }

  public void setScale(IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale scale) {
    this.scale = scale;
  }

  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources status(IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Status denotes the status subresource for CustomResources
   * @return status
  **/
  @ApiModelProperty(value = "Status denotes the status subresource for CustomResources")
  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus getStatus() {
    return status;
  }

  public void setStatus(IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources = (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources) o;
    return Objects.equals(this.scale, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources.scale) &&
        Objects.equals(this.status, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scale, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources {\n");
    
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

