/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sApiAutoscalingV2beta2CrossVersionObjectReference;
import io.swagger.client.model.IoK8sApiAutoscalingV2beta2MetricIdentifier;
import io.swagger.client.model.IoK8sApiAutoscalingV2beta2MetricValueStatus;
import java.io.IOException;

/**
 * ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 */
@ApiModel(description = "ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).")

public class IoK8sApiAutoscalingV2beta2ObjectMetricStatus {
  @SerializedName("current")
  private IoK8sApiAutoscalingV2beta2MetricValueStatus current = null;

  @SerializedName("describedObject")
  private IoK8sApiAutoscalingV2beta2CrossVersionObjectReference describedObject = null;

  @SerializedName("metric")
  private IoK8sApiAutoscalingV2beta2MetricIdentifier metric = null;

  public IoK8sApiAutoscalingV2beta2ObjectMetricStatus current(IoK8sApiAutoscalingV2beta2MetricValueStatus current) {
    this.current = current;
    return this;
  }

   /**
   * current contains the current value for the given metric
   * @return current
  **/
  @ApiModelProperty(required = true, value = "current contains the current value for the given metric")
  public IoK8sApiAutoscalingV2beta2MetricValueStatus getCurrent() {
    return current;
  }

  public void setCurrent(IoK8sApiAutoscalingV2beta2MetricValueStatus current) {
    this.current = current;
  }

  public IoK8sApiAutoscalingV2beta2ObjectMetricStatus describedObject(IoK8sApiAutoscalingV2beta2CrossVersionObjectReference describedObject) {
    this.describedObject = describedObject;
    return this;
  }

   /**
   * Get describedObject
   * @return describedObject
  **/
  @ApiModelProperty(required = true, value = "")
  public IoK8sApiAutoscalingV2beta2CrossVersionObjectReference getDescribedObject() {
    return describedObject;
  }

  public void setDescribedObject(IoK8sApiAutoscalingV2beta2CrossVersionObjectReference describedObject) {
    this.describedObject = describedObject;
  }

  public IoK8sApiAutoscalingV2beta2ObjectMetricStatus metric(IoK8sApiAutoscalingV2beta2MetricIdentifier metric) {
    this.metric = metric;
    return this;
  }

   /**
   * metric identifies the target metric by name and selector
   * @return metric
  **/
  @ApiModelProperty(required = true, value = "metric identifies the target metric by name and selector")
  public IoK8sApiAutoscalingV2beta2MetricIdentifier getMetric() {
    return metric;
  }

  public void setMetric(IoK8sApiAutoscalingV2beta2MetricIdentifier metric) {
    this.metric = metric;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiAutoscalingV2beta2ObjectMetricStatus ioK8sApiAutoscalingV2beta2ObjectMetricStatus = (IoK8sApiAutoscalingV2beta2ObjectMetricStatus) o;
    return Objects.equals(this.current, ioK8sApiAutoscalingV2beta2ObjectMetricStatus.current) &&
        Objects.equals(this.describedObject, ioK8sApiAutoscalingV2beta2ObjectMetricStatus.describedObject) &&
        Objects.equals(this.metric, ioK8sApiAutoscalingV2beta2ObjectMetricStatus.metric);
  }

  @Override
  public int hashCode() {
    return Objects.hash(current, describedObject, metric);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiAutoscalingV2beta2ObjectMetricStatus {\n");
    
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    describedObject: ").append(toIndentedString(describedObject)).append("\n");
    sb.append("    metric: ").append(toIndentedString(metric)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

