/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1ListMeta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CustomResourceDefinitionList is a list of CustomResourceDefinition objects.
 */
@ApiModel(description = "CustomResourceDefinitionList is a list of CustomResourceDefinition objects.")

public class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("items")
  private List<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition> items = new ArrayList<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition>();

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private IoK8sApimachineryPkgApisMetaV1ListMeta metadata = null;

  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList items(List<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition> items) {
    this.items = items;
    return this;
  }

  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList addItemsItem(IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Items individual CustomResourceDefinitions
   * @return items
  **/
  @ApiModelProperty(required = true, value = "Items individual CustomResourceDefinitions")
  public List<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition> getItems() {
    return items;
  }

  public void setItems(List<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition> items) {
    this.items = items;
  }

  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList metadata(IoK8sApimachineryPkgApisMetaV1ListMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public IoK8sApimachineryPkgApisMetaV1ListMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(IoK8sApimachineryPkgApisMetaV1ListMeta metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList = (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList) o;
    return Objects.equals(this.apiVersion, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList.apiVersion) &&
        Objects.equals(this.items, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList.items) &&
        Objects.equals(this.kind, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList.kind) &&
        Objects.equals(this.metadata, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, items, kind, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

