/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * APIServiceStatus contains derived information about an API server
 */
@ApiModel(description = "APIServiceStatus contains derived information about an API server")

public class IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus {
  @SerializedName("conditions")
  private List<IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition> conditions = null;

  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus conditions(List<IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition> conditions) {
    this.conditions = conditions;
    return this;
  }

  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus addConditionsItem(IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Current service state of apiService.
   * @return conditions
  **/
  @ApiModelProperty(value = "Current service state of apiService.")
  public List<IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition> getConditions() {
    return conditions;
  }

  public void setConditions(List<IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition> conditions) {
    this.conditions = conditions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus ioK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus = (IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus) o;
    return Objects.equals(this.conditions, ioK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus.conditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus {\n");
    
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

