/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1ObjectMeta;
import io.swagger.client.model.IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec;
import io.swagger.client.model.IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus;
import java.io.IOException;

/**
 * APIService represents a server for a particular GroupVersion. Name must be \&quot;version.group\&quot;.
 */
@ApiModel(description = "APIService represents a server for a particular GroupVersion. Name must be \"version.group\".")

public class IoK8sKubeAggregatorPkgApisApiregistrationV1APIService {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata = null;

  @SerializedName("spec")
  private IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec spec = null;

  @SerializedName("status")
  private IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus status = null;

  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIService apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIService kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIService metadata(IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public IoK8sApimachineryPkgApisMetaV1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIService spec(IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec spec) {
    this.spec = spec;
    return this;
  }

   /**
   * Spec contains information for locating and communicating with a server
   * @return spec
  **/
  @ApiModelProperty(value = "Spec contains information for locating and communicating with a server")
  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec getSpec() {
    return spec;
  }

  public void setSpec(IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec spec) {
    this.spec = spec;
  }

  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIService status(IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Status contains derived information about an API server
   * @return status
  **/
  @ApiModelProperty(value = "Status contains derived information about an API server")
  public IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus getStatus() {
    return status;
  }

  public void setStatus(IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sKubeAggregatorPkgApisApiregistrationV1APIService ioK8sKubeAggregatorPkgApisApiregistrationV1APIService = (IoK8sKubeAggregatorPkgApisApiregistrationV1APIService) o;
    return Objects.equals(this.apiVersion, ioK8sKubeAggregatorPkgApisApiregistrationV1APIService.apiVersion) &&
        Objects.equals(this.kind, ioK8sKubeAggregatorPkgApisApiregistrationV1APIService.kind) &&
        Objects.equals(this.metadata, ioK8sKubeAggregatorPkgApisApiregistrationV1APIService.metadata) &&
        Objects.equals(this.spec, ioK8sKubeAggregatorPkgApisApiregistrationV1APIService.spec) &&
        Objects.equals(this.status, ioK8sKubeAggregatorPkgApisApiregistrationV1APIService.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sKubeAggregatorPkgApisApiregistrationV1APIService {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

