/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sApiAuthorizationV1NonResourceAttributes;
import io.swagger.client.model.IoK8sApiAuthorizationV1ResourceAttributes;
import java.io.IOException;

/**
 * SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
 */
@ApiModel(description = "SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set")

public class IoK8sApiAuthorizationV1SelfSubjectAccessReviewSpec {
  @SerializedName("nonResourceAttributes")
  private IoK8sApiAuthorizationV1NonResourceAttributes nonResourceAttributes = null;

  @SerializedName("resourceAttributes")
  private IoK8sApiAuthorizationV1ResourceAttributes resourceAttributes = null;

  public IoK8sApiAuthorizationV1SelfSubjectAccessReviewSpec nonResourceAttributes(IoK8sApiAuthorizationV1NonResourceAttributes nonResourceAttributes) {
    this.nonResourceAttributes = nonResourceAttributes;
    return this;
  }

   /**
   * NonResourceAttributes describes information for a non-resource access request
   * @return nonResourceAttributes
  **/
  @ApiModelProperty(value = "NonResourceAttributes describes information for a non-resource access request")
  public IoK8sApiAuthorizationV1NonResourceAttributes getNonResourceAttributes() {
    return nonResourceAttributes;
  }

  public void setNonResourceAttributes(IoK8sApiAuthorizationV1NonResourceAttributes nonResourceAttributes) {
    this.nonResourceAttributes = nonResourceAttributes;
  }

  public IoK8sApiAuthorizationV1SelfSubjectAccessReviewSpec resourceAttributes(IoK8sApiAuthorizationV1ResourceAttributes resourceAttributes) {
    this.resourceAttributes = resourceAttributes;
    return this;
  }

   /**
   * ResourceAuthorizationAttributes describes information for a resource access request
   * @return resourceAttributes
  **/
  @ApiModelProperty(value = "ResourceAuthorizationAttributes describes information for a resource access request")
  public IoK8sApiAuthorizationV1ResourceAttributes getResourceAttributes() {
    return resourceAttributes;
  }

  public void setResourceAttributes(IoK8sApiAuthorizationV1ResourceAttributes resourceAttributes) {
    this.resourceAttributes = resourceAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiAuthorizationV1SelfSubjectAccessReviewSpec ioK8sApiAuthorizationV1SelfSubjectAccessReviewSpec = (IoK8sApiAuthorizationV1SelfSubjectAccessReviewSpec) o;
    return Objects.equals(this.nonResourceAttributes, ioK8sApiAuthorizationV1SelfSubjectAccessReviewSpec.nonResourceAttributes) &&
        Objects.equals(this.resourceAttributes, ioK8sApiAuthorizationV1SelfSubjectAccessReviewSpec.resourceAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonResourceAttributes, resourceAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiAuthorizationV1SelfSubjectAccessReviewSpec {\n");
    
    sb.append("    nonResourceAttributes: ").append(toIndentedString(nonResourceAttributes)).append("\n");
    sb.append("    resourceAttributes: ").append(toIndentedString(resourceAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

