/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MetricValueStatus holds the current value for a metric
 */
@ApiModel(description = "MetricValueStatus holds the current value for a metric")

public class IoK8sApiAutoscalingV2beta2MetricValueStatus {
  @SerializedName("averageUtilization")
  private Integer averageUtilization = null;

  @SerializedName("averageValue")
  private String averageValue = null;

  @SerializedName("value")
  private String value = null;

  public IoK8sApiAutoscalingV2beta2MetricValueStatus averageUtilization(Integer averageUtilization) {
    this.averageUtilization = averageUtilization;
    return this;
  }

   /**
   * currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.
   * @return averageUtilization
  **/
  @ApiModelProperty(value = "currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.")
  public Integer getAverageUtilization() {
    return averageUtilization;
  }

  public void setAverageUtilization(Integer averageUtilization) {
    this.averageUtilization = averageUtilization;
  }

  public IoK8sApiAutoscalingV2beta2MetricValueStatus averageValue(String averageValue) {
    this.averageValue = averageValue;
    return this;
  }

   /**
   * averageValue is the current value of the average of the metric across all relevant pods (as a quantity)
   * @return averageValue
  **/
  @ApiModelProperty(value = "averageValue is the current value of the average of the metric across all relevant pods (as a quantity)")
  public String getAverageValue() {
    return averageValue;
  }

  public void setAverageValue(String averageValue) {
    this.averageValue = averageValue;
  }

  public IoK8sApiAutoscalingV2beta2MetricValueStatus value(String value) {
    this.value = value;
    return this;
  }

   /**
   * value is the current value of the metric (as a quantity).
   * @return value
  **/
  @ApiModelProperty(value = "value is the current value of the metric (as a quantity).")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiAutoscalingV2beta2MetricValueStatus ioK8sApiAutoscalingV2beta2MetricValueStatus = (IoK8sApiAutoscalingV2beta2MetricValueStatus) o;
    return Objects.equals(this.averageUtilization, ioK8sApiAutoscalingV2beta2MetricValueStatus.averageUtilization) &&
        Objects.equals(this.averageValue, ioK8sApiAutoscalingV2beta2MetricValueStatus.averageValue) &&
        Objects.equals(this.value, ioK8sApiAutoscalingV2beta2MetricValueStatus.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageUtilization, averageValue, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiAutoscalingV2beta2MetricValueStatus {\n");
    
    sb.append("    averageUtilization: ").append(toIndentedString(averageUtilization)).append("\n");
    sb.append("    averageValue: ").append(toIndentedString(averageValue)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

