/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.13.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.IoK8sApiBatchV1beta1CronJob;
import io.swagger.client.model.IoK8sApiBatchV1beta1CronJobList;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIResourceList;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1DeleteOptions;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Patch;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Status;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1WatchEvent;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BatchV1beta1Api
 */
@Ignore
public class BatchV1beta1ApiTest {

    private final BatchV1beta1Api api = new BatchV1beta1Api();

    
    /**
     * 
     *
     * create a CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBatchV1beta1NamespacedCronJobTest() throws ApiException {
        String namespace = null;
        IoK8sApiBatchV1beta1CronJob body = null;
        Boolean includeUninitialized = null;
        String pretty = null;
        String dryRun = null;
        IoK8sApiBatchV1beta1CronJob response = api.createBatchV1beta1NamespacedCronJob(namespace, body, includeUninitialized, pretty, dryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBatchV1beta1CollectionNamespacedCronJobTest() throws ApiException {
        String namespace = null;
        Boolean includeUninitialized = null;
        String pretty = null;
        String _continue = null;
        String fieldSelector = null;
        String labelSelector = null;
        Integer limit = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteBatchV1beta1CollectionNamespacedCronJob(namespace, includeUninitialized, pretty, _continue, fieldSelector, labelSelector, limit, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBatchV1beta1NamespacedCronJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        IoK8sApimachineryPkgApisMetaV1DeleteOptions body = null;
        String dryRun = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        String propagationPolicy = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteBatchV1beta1NamespacedCronJob(name, namespace, pretty, body, dryRun, gracePeriodSeconds, orphanDependents, propagationPolicy);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get available resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBatchV1beta1APIResourcesTest() throws ApiException {
        IoK8sApimachineryPkgApisMetaV1APIResourceList response = api.getBatchV1beta1APIResources();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBatchV1beta1CronJobForAllNamespacesTest() throws ApiException {
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApiBatchV1beta1CronJobList response = api.listBatchV1beta1CronJobForAllNamespaces(_continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBatchV1beta1NamespacedCronJobTest() throws ApiException {
        String namespace = null;
        Boolean includeUninitialized = null;
        String pretty = null;
        String _continue = null;
        String fieldSelector = null;
        String labelSelector = null;
        Integer limit = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApiBatchV1beta1CronJobList response = api.listBatchV1beta1NamespacedCronJob(namespace, includeUninitialized, pretty, _continue, fieldSelector, labelSelector, limit, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchBatchV1beta1NamespacedCronJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoK8sApimachineryPkgApisMetaV1Patch body = null;
        String pretty = null;
        String dryRun = null;
        IoK8sApiBatchV1beta1CronJob response = api.patchBatchV1beta1NamespacedCronJob(name, namespace, body, pretty, dryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchBatchV1beta1NamespacedCronJobStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoK8sApimachineryPkgApisMetaV1Patch body = null;
        String pretty = null;
        String dryRun = null;
        IoK8sApiBatchV1beta1CronJob response = api.patchBatchV1beta1NamespacedCronJobStatus(name, namespace, body, pretty, dryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readBatchV1beta1NamespacedCronJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        IoK8sApiBatchV1beta1CronJob response = api.readBatchV1beta1NamespacedCronJob(name, namespace, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readBatchV1beta1NamespacedCronJobStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        IoK8sApiBatchV1beta1CronJob response = api.readBatchV1beta1NamespacedCronJobStatus(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceBatchV1beta1NamespacedCronJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoK8sApiBatchV1beta1CronJob body = null;
        String pretty = null;
        String dryRun = null;
        IoK8sApiBatchV1beta1CronJob response = api.replaceBatchV1beta1NamespacedCronJob(name, namespace, body, pretty, dryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified CronJob
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceBatchV1beta1NamespacedCronJobStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoK8sApiBatchV1beta1CronJob body = null;
        String pretty = null;
        String dryRun = null;
        IoK8sApiBatchV1beta1CronJob response = api.replaceBatchV1beta1NamespacedCronJobStatus(name, namespace, body, pretty, dryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * watch individual changes to a list of CronJob. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void watchBatchV1beta1CronJobListForAllNamespacesTest() throws ApiException {
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1WatchEvent response = api.watchBatchV1beta1CronJobListForAllNamespaces(_continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * watch changes to an object of kind CronJob. deprecated: use the &#39;watch&#39; parameter with a list operation instead, filtered to a single item with the &#39;fieldSelector&#39; parameter.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void watchBatchV1beta1NamespacedCronJobTest() throws ApiException {
        String name = null;
        String namespace = null;
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1WatchEvent response = api.watchBatchV1beta1NamespacedCronJob(name, namespace, _continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * watch individual changes to a list of CronJob. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void watchBatchV1beta1NamespacedCronJobListTest() throws ApiException {
        String namespace = null;
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1WatchEvent response = api.watchBatchV1beta1NamespacedCronJobList(namespace, _continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
}
